branches:
  only:
    - master

language: cpp
compiler: 
  - g++
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

before_script: "bash -c ./download-gtest.sh"
script: "which $CXX; cmake --debug-output -DBuildTests=ON -DEnableSSE=OFF -DCMAKE_CXX_COMPILER=$CXX . && make && ./tests"

