branches:
  only:
    - master

language: cpp
compiler: 
  - g++

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

install:
- mkdir -p "$HOME/bin" && rm -f "$HOME/bin/g++" && ln -s /usr/bin/g++-4.9 "$HOME/bin/g++"

script: "autoreconf -v && ./configure && make && ./test"

