env:
  global:
    secure: "Xtwlf0NPrlw6NpdLV1iIgs1f8aWK5lqGmfg1iCDQrsuYhHl7/3tldUIS/I1YMyxPOQHRuaBhFPBgv7YMcDl/1Hss001xm3ILbtgDNBCzUG6v4ZgZsB3qUaWWTegw/y9UwQbjqD720on9Wpqr6Rr8XqjaBxn+siWRN5io/sQj6w2o74xn2/+rIol+ei/XLtdmMHoayO24xN1dAAv14/0kCqH1L7Atij33grjyFIF3M6fyVlZzruoBTQVLfq/J19lkHtCf6ItjC2f2gorXYgGBfNQaWYz00U/fIHUgtLo/7QtvNsofb+J39jOeG97I4P0Nwu+2Jhn3O1wU0pnnCl99qLpDbYrzch/TaRWVau3khjLG2/1twLImdJn4nWXeBuX5S4Kazr3s0hGF2wBfFPDQU9izg/3nxC6gIT+o+BJvLcdJsio3SDdN2KorEuQrteRJsGXSAgOebBnsDaVkiKy/QDj6V4ZDYdkZ9G5OwsAAGpfDLDkRRwquCW83zUNBicReYOpervdtIDBQg2KbNdb6lIR+5b16+uggeoFV1O/+2dfKYj5MqXwtSRGRwCZ5ArFjWN1ARI3pObjrutsX6PoZdYL6Y4d6UYm7koI+25dkY3GCPCY5KB09ory6zIQ7vvfSHOs4LZZqdS6jDVtCjgWscwwgqEjmOA5uWGYWmf+yDs8="

branches:
  only:
    - master

language: cpp
compiler: 
  - g++
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang

install:
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- make -C lcov-1.11/ install PREFIX=~/lcov
- gem install coveralls-lcov
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

before_script:
- cmake --version
- $CXX --version
- ~/lcov/usr/bin/lcov --directory . --zerocounters
 
script: 
- ulimit -c unlimited -S # enable core files
- mkdir -p build
- (cd build && cmake -DCoverage=ON -DBuildTests=ON -DBuildLargeTests=OFF -DBuildExamples=ON -DBuildTools=ON -DEnableSSE=OFF -DCMAKE_CXX_COMPILER=$CXX ..)
- (cd build && make)
- (cd build/tests && ctest -V)

after_success:
- ~/lcov/usr/bin/lcov --directory . --capture --output-file coverage.info # capture coverage info
- ~/lcov/usr/bin/lcov --remove coverage.info 'tests/*' '/usr/*' 'examples/*' 'tools/*' --output-file coverage.info # filter out system and test code
- ~/lcov/usr/bin/lcov --list coverage.info # debug before upload
- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

after_failure:
- COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
- echo; # if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" bin/arangod -ex "thread apply all bt" -ex "set pagination 0" -batch; fi 

