branches:
  only:
    - master

language: cpp
compiler: 
  - g++
  - clang

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

script: "which $CXX; mkdir -p build; (cd build && cmake -DBuildTests=ON -DEnableSSE=OFF -DCMAKE_CXX_COMPILER=$CXX .. && make && ./testsBuilder && ./testsCollection && ./testsDumper && ./testsFiles && ./testsIterator && ./testsLookup && ./testsParser && ./testsSlice && ./testsType)"

