version: 1.0.{build}
branches:
  only:
    - master
configuration: Release
build:
build_script:
  - md %APPVEYOR_BUILD_FOLDER%\build
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G "Visual Studio 12 Win64" -DEnableTests=ON -DEnableExamples=ON -DEnableLargeTests=OFF ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win64" velocypack.sln
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build\tests
  - ctest -V 
