version: 1.0.{build}
branches:
  only:
    - master
configuration: Release
build:
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - cmake -G "Visual Studio 12 Win64" -DBuildTests=ON -DBuildExamples=ON -DBuildLargeTests=OFF -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\build\tests
  - ctest -V 
